import os
from building import *

cwd = GetCurrentDir()
list = os.listdir(cwd)

target_dirs = [
    "common",
    str(GetConfigValue('LCD_HOR_RES_MAX'))+'x'+str(GetConfigValue('LCD_VER_RES_MAX')),
]

objs_ezip = []
objs_no_ezip = []

for root, dirs, files in os.walk(cwd):
    for file in files:
        if not file.endswith('.png'):
            continue
        file_path = os.path.relpath(os.path.join(root, file), cwd)

        contains_target_dir = False
        for target_dir in target_dirs:
            if target_dir in file_path:
                contains_target_dir = True
                break
        if not contains_target_dir:
            continue

        if 'zip' in file_path:
            if GetDepend('LV_USE_EZIP'):
                objs_ezip.append(file_path)
            else:
                objs_no_ezip.append(file_path)
        elif 'no_zip' in file_path:
            objs_no_ezip.append(file_path)

# color_fmt, file_fmt, section_name
if 16 == GetConfigValue('LV_COLOR_DEPTH'):
    img_flags = '-rgb565'
else:
    img_flags = '-rgb888'

img_flags += ' -section ROM3_IMG -lvgl_version 9'

objs = Env.ImgResource(objs_no_ezip, img_flags+' -cfile 1 -dpt 1')
objs += Env.ImgResource(objs_ezip, img_flags+' -cfile 2 -dpt 1')

objs = DefineGroup('res', objs, depend=[''])

Return('objs')
