from building import *
import os
font_objs = []

cwd = GetCurrentDir()
font_file = os.path.join(cwd, 'DroidSansFallback.ttf')

if not os.path.exists(font_file):
    print(f"Warning: Font file does not exist: {font_file}")
    font_objs = []
else:
    font_objs = Env.ConvertFont(font_file, 'DroidSansFallback')
    font_objs = DefineGroup('res', font_objs, depend=[''])

Return('font_objs')
