from building import *
import os
import rtconfig

# Check PONY
PONY_DIR = os.getenv('PONY_DIR')
if not PONY_DIR:
    print("Please run export.ps1 in pony_sf dir to set environment.")
    exit()
Export('PONY_DIR')

SIFLI_SDK = os.getenv('SIFLI_SDK')

# Prepare environment.
PrepareEnv()

################################## change rtconfig.xxx to customize build ########################################

# Add bootloader project
AddBootLoader(SIFLI_SDK, rtconfig.CHIP)

# Set default compile options
SifliEnv()

TARGET = rtconfig.OUTPUT_DIR + rtconfig.TARGET_NAME + '.' + rtconfig.TARGET_EXT
# Prepare building environment
objs = PrepareBuilding(None)
env = GetCurrentEnv()

# Build application.
DoBuilding(TARGET, objs)

# Add flash table buld.
AddFTAB(SIFLI_SDK, rtconfig.CHIP)

# Generate download .bat script
GenDownloadScript(env)
