import os
from building import *

cwd = GetCurrentDir()
objs = []
list = os.listdir(cwd)

# Add pony
Import('PONY_DIR')
objs.extend(SConscript(os.path.join(PONY_DIR, 'SConscript'), variant_dir="pony", duplicate=0))

# Add SDK
Import('SIFLI_SDK')
objs.extend(SConscript(os.path.join(SIFLI_SDK, 'SConscript'), variant_dir="sifli_sdk", duplicate=0))

# Add application source code
objs.extend(SConscript(cwd+'/../src/SConscript', variant_dir="src", duplicate=0))

Return('objs')
